### ISSUE TITLE
Cannot create ressource Azure with pulumi using azapi

### ISSUE THREAD

**Issue by Kmougari** [dirien/pulumi-azapi#55]
When creatiung cost management we always have this problem "error: Preview failed: diffing urn:pulumi:sandbox::finops-examples::azapi:index/resource:Resource::finops-year: resource name can't be empty, either specifying a default name or a resource name"

We have tested this when trying to create other azure ressource and still have the same problem

<img width="852" alt="image" src="https://github.com/dirien/pulumi-azapi/assets/98874426/54ab3b90-bf6d-44af-967f-1febe821ce94">

**Comment by Kmougari** [comment]
Find code example :

```import * as pulumi from "@pulumi/pulumi";
import * as azure_native from "@pulumi/azure-native";
import * as costmgt from "@pulumi/azure-native/costmanagement/v20221001";
import * as azapi from "@ediri/azapi";
import {jsonStringify} from "@pulumi/pulumi";

// const resourceGroup = new azure_native.resources.ResourceGroup("resource-group2", {
//     location: 'francecentral',
//     resourceGroupName: "rg-pj-test",
// });

new azapi.Resource('finops-year', 
{
    type: 'Microsoft.CostManagement/views@2023-03-01',
    name: 'finops-year',
    //parentId: subscription()
    //location: "FranceCentral",
    //parentId: '/subscriptions/1c2c2023-f6a2-4224-8d69-2a9a12a1e3b3',
    parentId: '/',
    ignoreCasing: true,
    body: jsonStringify(
        {  
            properties: {
               //scope: '/subscriptions/1c2c2023-f6a2-4224-8d69-2a9a12a1e3b3',
               displayName: "finops: This year",
               query: {
                 type: "Usage",
                 timeframe: "Last12Months",
                 dataSet: {
                   granularity: "Monthly",
                   aggregation: {
                    totalCost: {
                      name: "PreTaxCost",
                      function: "Sum"
                    }
                  },
                  grouping: [],
                  sorting: [
                    {
                      direction: "Ascending",
                      name: "UsageDate"
                    }
                  ]
                }
              },
              chart: "StackedColumn",
              dateRange: "Last12Months",
              accumulated: "true",
              metric: "ActualCost",
               pivots: [
                 {
                    type: "Dimension",
                    name: "ServiceName"
                 },
                 {
                     name: "ResourceGroupName",
                     type: "Dimension",
                 },
                 {
                    type: "TagKey",
                    name: "swaggerTagKey"
                 }
               ]
            }  
        }
    )
})
```

**Comment by dirien** [comment]
Hey @Kmougari,

Did you set the `parentId` to the `resourceGroup.id`?

**Comment by olivierbayet** [comment]
Hello @dirien,

I have the same issue, here is my code based on [your TS example](https://github.com/dirien/pulumi-azapi/blob/main/examples/azapi-ts/index.ts).

As you can see parentId is correctly set :

```
import * as core from "@pulumi/azure/core";
import * as azapi from "@ediri/azapi";
import {jsonStringify} from "@pulumi/pulumi";

// const resourceGroup = new azure_native.resources.ResourceGroup("resource-group2", {
//     location: 'francecentral',
//     resourceGroupName: "rg-pj-test",
// });

const location = 'France Central';

// Create an Azure Resource Group
const resourceGroup = new core.ResourceGroup('rg-test-azapi', {
    location: location,
});

const appServicePlan = new azapi.Resource('app-service-plan-azapi', {
    name: 'app-service-plan',
    type: 'Microsoft.Web/serverfarms@2020-06-01',
    parentId: resourceGroup.id,
    ignoreCasing: true,
    body: jsonStringify(
        {
            sku: {
                name: "F1",
            },
            properties: {
                reserved: true,
            },
            kind: "linux",
            location: location,
        }
    ),
    responseExportValues: [
        "*"
    ]
})
```

I get the same error at pulumi preview : "resource name can't be empty, either specifying a default name or a resource name"
<img width="1461" alt="image" src="https://github.com/dirien/pulumi-azapi/assets/26431572/183ba3ee-66e9-4818-b6fb-803946259518">

**Comment by dirien** [comment]
hey @olivierbayet,

I could reconstruct your error and linked this issue with an existing issue in the `pulumi-terraform-bridge` 

As a workaround, I would like to ask you to downgrade the provider to version 1.2.0, of course only if it's possible for you.

**Comment by olivierbayet** [comment]
> hey @olivierbayet,
> 
> I could reconstruct your error and linked this issue with an existing issue in the `pulumi-terraform-bridge`
> 
> As a workaround, I would like to ask you to downgrade the provider to version 1.2.0, of course only if it's possible for you.

Hey @dirien,

I manage to make it work with version 1.2.9.
It did not work at first `pulumi up`though.

I first faced problem to get the package :
```
GitHub rate limit exceeded for https://api.github.com/repos/dirien/pulumi-azapi/releases/tags/v1.2.9
```
Then an issue with authentication :
```
     Type                         Name                    Status                       Info
 +   pulumi:pulumi:Stack          azapi-examples-sandbox  **creating failed (3s)**     1 error
 +   ├─ azure:core:ResourceGroup  rg-test-azapi           created (1s)
 +   └─ azapi:index:Resource      app-service-plan-azapi  **creating failed**          1 error


Diagnostics:
  pulumi:pulumi:Stack (azapi-examples-sandbox):
    error: update failed

  azapi:index:Resource (app-service-plan-azapi):
    error: 1 error occurred:
    	* checking for presence of existing Resource: (ResourceId "/subscriptions/xxx/resourceGroups/rg-test-azapi22233d7a/providers/Microsoft.Web/serverfarms/app-service-plan" / Api Version "2020-06-01"): DefaultAzureCredential authentication failed
    GET http://169.254.169.254/metadata/identity/oauth2/token
    --------------------------------------------------------------------------------
    RESPONSE 503 Service Unavailable
    --------------------------------------------------------------------------------
   
```
    
But after some retries, it succeeded

```
     Type                     Name                    Status
     pulumi:pulumi:Stack      azapi-examples-sandbox
 +   └─ azapi:index:Resource  app-service-plan-azapi  created (6s)


Resources:
    + 1 created
    2 unchanged

Duration: 32s
```    

Let see if @Kmougari has same behaviour.

**Comment by dirien** [comment]
@olivierbayet Awesome, that at least you got it up and running! See linked issue for fixing the root cause.

Just a hint, we have the new `azure-native` v2 package, so you should get later API versions! No need to use the `azapi` provider! CC: @Kmougari 

https://www.pulumi.com/registry/packages/azure-native-v2/installation-configuration/

**Comment by Kmougari** [comment]
Thanks for the feedback @dirien , I got the same result then @olivierbayet . However the v1.103.0 of pulumi provider does not allow to update the daterange yet. We will have to wait for new version of the provider to be able to do it with azure nativeThanks

**Comment by Kmougari** [comment]
Hower the v1.103.0 of pulumi provider does not allow to update the daterange yet. We will have to wait for new version of the provider to be able to do it with azure native

**Comment by dirien** [comment]
Hey @Kmougari and @olivierbayet,

Version `1.8.1` of the `pulumi-azapi` provider fixes the issue:

![image](https://github.com/dirien/pulumi-azapi/assets/38325136/f29bbe22-41ee-45a9-97a2-bec395d88075)

Thanks @t0yv0 for the fix!

**Comment by t0yv0** [comment]
Brilliant, thank you for confirming!
